services:
  postgres:
    image: postgres:15-alpine
    container_name: payments_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: payments_redis
    restart: always
    ports:
      - "6379:6379"

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment_service
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/payment_db?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: "super-secret-payment-key"
    depends_on:
      - postgres
      - redis

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification_service
    restart: always
    ports:
      - "3002:3002"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      PAYMENT_SERVICE_URL: "http://payment-service:3001"
      JWT_SECRET: "super-secret-payment-key"
      PORT: 3000
    depends_on:
      - payment-service

volumes:
  postgres_data:
